### ISSUE TITLE
Pre-load assets

### ISSUE THREAD

**Issue by kdinluks** [PredixDev/px-context-browser#10]
An option to pre-load a number of levels of the asset hierarchy would make it much more neat than having to wait every level to be loaded when the user clicks on an asset.
For example it could load up to 5 levels down the hierarchy and when the user opens the level 4 it would pre-load the next 5 levels (5 to 10).
I know that there are use cases where you will need to do level by level load but we could have both options to choose from.

**Comment by runn-vermel** [comment]
Hi @kdinluks,

Thank you for your suggestion. WE've considered this in the past, and have consulted the Predix Asset Team, and decided against this.

The problem that we faced was that you never know the possible future path the user will take. this means that going "levels in" has to be done on each available item, which can translate into 100s of unnecessary calls.

Please let me know if this doesn't make sense.
