### ISSUE TITLE
px-context-browser bug with multiple nested children

### ISSUE THREAD

**Issue by ArslanBouzid** [PredixDev/px-context-browser#14]
[https://forum.predix.io/questions/9827/px-context-browser-bug-with-nest-children.html](url)

I got a solution for this "bug ???" that I can push.

---- inline post ----

Hello guys,

I got this weird bug when loading a json file (using **iron-ajax**) and pass it to the **px-context-browser** browser-context property.

I used this very simple json:

    {
      "data": [{
        "name": "test 1",
        "id": "001-1",
        "isOpenable": false,
        "children": [{
          "name": "Child 1-1",
          "id": "001-1a",
          "isOpenable": true,
          "selectedAsset": true
        }]
      }, {
        "name": "test 2",
        "id": "001-2",
        "isOpenable": false,
        "children": [{
          "name": "Child 2-1",
          "id": "001-2a",
          "isOpenable": true
        }]
      }]
    }

And this is what I got:

![1330-untitled](https://cloud.githubusercontent.com/assets/7040747/17202601/93826ee0-549a-11e6-8938-2a0f64240730.png)

And without setting "selectedAsset":

![1341-untitled](https://cloud.githubusercontent.com/assets/7040747/17202610/9db1445e-549a-11e6-9ab8-868c2819bfbd.png)

I also tried with a more complex json without success, all the nested children got added... 
I think that this control keeps adding data and is expecting us to pass the first level of the json and rely on the **getChildren callback** to get the remaining data... or I may be wrong. 

I also checked this file [https://github.com/PredixDev/px-context-browser/blob/master/directContext.json][3], but it didn't work when I added children to the first element ( "identifier": "001-1").

Cheers

  [1]: /storage/temp/1330-untitled.png
  [2]: /storage/temp/1341-untitled.png
  [3]: https://github.com/PredixDev/px-context-browser/blob/master/directContext.json

**Comment by runn-vermel** [comment]
HI @ArslanBouzid 

Apart from that first image - which does look odd, I'm not sure what the issue that you're reporting is.

there are two ways of passing data into the context browser:
1. initial Context
2. Direct Context

**## Initial Context**
with Initial context you only pass the first level (i.e. the left column). it does NOT expect any children and DOES rely on the getChildren callback.

**## Direct Context**
This method assumes 2 things:
1. one of the objects in the json file has a "selectedAsset" property
2. the objects passed in are IN THE DIRECT PATH OF THE SELECTED ASSET. This is done to ensure the context browser loads only what's needed, as opposed to (possible) 1000s of items.

I hope this helps clarify things a bit. If there's still an issue i haven't addressed, i apologize - please feel free to clarify further.

**Comment by ArslanBouzid** [comment]
Hello @runn-vermel,

Thanks for the quick feedback.

As you may have noticed, I'm using the DirectContext (for now, I'll be using the intial context approach later), and yet if more than one node has children, I got this weird behavior with and without setting "selectedAsset".

I've attached the modified **px-context-browser** file that fixes my issue (you'll have to specify "hasChildren": true to all nodes that have children).

PS: I've an issue uploading a zip file, you should change the extension to .js

![px-context-browser js](https://cloud.githubusercontent.com/assets/7040747/17240748/9dffc952-556d-11e6-9d19-074ca7034e2b.png)

**Comment by runn-vermel** [comment]
Hi @ArslanBouzid - can you please submit this as a pull request? I can't acces the file you attached.

Thanks!

**Comment by runn-vermel** [comment]
Pr submitted and accepted as version 1.0.6. closing issue
