### ISSUE TITLE
Not able to see the header Panel on Opera Browser

### ISSUE THREAD

**Issue by akshayjk** [PredixDev/px-context-browser#15]
I am not able to see the Header Panel while on Opera Browser, when the Modal is active.

**Comment by runn-vermel** [comment]
HI @akshayjk,

Thank you for your issue - We currently support:
the last 2 chrome and firefox and safari versions, and IE10/11/edge - Opera is not supported, and should be used at your own discretion.

**Comment by akshayjk** [comment]
Hello run-vermel. Could you please list down the version numbers supported instead of "last two" versions on chrome since the same problem I am facing on chrome version  Version 52.0.2743.116 m
I can see the header panel now on the px-context-browser demo page from chrome.

**Comment by runn-vermel** [comment]
Hi @akshayjk,

Thanks for pointing this out (and staying with it!). 

Chrome 52 changed its behavior from 51 regarding CSS, which was causing this bug.

I fixed the bug, and it's available in version 1.0.7.

Please let us know if you find anything else :)
