### ISSUE TITLE
Allow the px-context-browser to be disabled

### ISSUE THREAD

**Issue by benmak11** [PredixDev/px-context-browser#22]
Is there a property that is in the works or streamlined in the backlog for disabling the context-browser?

**Comment by randyaskin** [comment]
Just to clarify, by "disabled" do you mean that you still want the context browser to be visible on the page, but have it grayed out or something and non-interactive?

**Comment by benmak11** [comment]
@randyaskin yes that's exactly what I am asking for. Thank you!

**Comment by 1mayur** [comment]
@randyaskin I would love to build this enhancement, Let me know if you would like me to contribute to this?

**Comment by runn-vermel** [comment]
@1mayur - let's run this by our designers first, and if they give the thumbs up, it's all yours :)

**Comment by 1mayur** [comment]
@runn-vermel Thanks. Will wait for the response

**Comment by runn-vermel** [comment]
review requested from design team

**Comment by randyaskin** [comment]
To be in line with our other disabled buttons, I would expect:

1. A new property should be added for "disabled" (boolean, value false by default)
2. Asset and parent asset text color should be exposed as a new style variable (--px-cb-text-color--disabled), which should default to $gray4
3. The "fa-caret-down" icon on the right should be hidden
4. The cursor should change from pointer to "not-allowed"
5. The click event should be ignored so the modal is not invoked

**Comment by 1mayur** [comment]
@randyaskin Okay, Thanks

**Comment by 1mayur** [comment]
@randyaskin @runn-vermel Created the PR with the feature and also updated the index.html page for demo.
