### ISSUE TITLE
Are we not required to .appendChild after .importNode of the <template>

### ISSUE THREAD

**Issue by Ishank-dubey** [PredixDev/px-context-browser#25]
I am using Predix Polymer components in a micro App which uses Angular + Polymer. My problem that the app crashes when opened on Firefox or IE. When I do a clone(like say-  `clone = document.importNode(t.content, true);`) of the template container and append(like - `conatiner.appendChild(clone);`) to  the parent explicitly the App works in FF and IE as well. Any directions?
Also may see [this](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/template)

**Comment by runn-vermel** [comment]
Hi There,

I'm sorry you're having issues, however, i'm not sure how this is an issue on the context browser??
