### ISSUE TITLE
404s for font-awesome file references in px-context-browser

### ISSUE THREAD

**Issue by navamara** [PredixDev/px-context-browser#27]
# 404s for font-awesome file references in px-context-browser 

Hi,

We are noticing 404s for font awesome font files when using px-context-browser
version 1.4.5

## Expected behavior and actual behavior:
No 404s
## Steps to reproduce the problem:
Install version 1.4.5 of px-context-browser and open the demo page, use 
## Environment (_component version number, Browser (including version), operating system, hardware, etc_):
Windows7
IE 11

![fa-404](https://cloud.githubusercontent.com/assets/5941696/21442511/150edae4-c853-11e6-9eb7-4a403402e0f7.png)

**Comment by mdwragg** [comment]
Hi, can you show us this error outside of your app please? We can't recreate this on our various staging sites or locally.

And can you confirm it is only IE11 that is affected?

Thanks.

**Comment by runn-vermel** [comment]
Hi @navamara - My guess is that you upgraded px-context-browser, but haven't removed your old bower_components folder. i would recommend deleting the bower_components folder, making sure all of your px components are pointing to the latest version ( we did a pretty big re-haul of our components to make them themable ), and doing a bower install.

Please let us know if this didn't work - like Martin said, a codepen would be the best way for us to see this.

**Comment by runn-vermel** [comment]
closing issue - please re-open if the above instructions don't work for you.

**Comment by dwarhya** [comment]
Hi,

I have the same issue - except I do not get errors in the browser log - just the font is wrong (not GE Inspira).  I cleared out bower_components completely to get new versions of px-vis-timeseries, px-context-browser etc (per this [forum post](http://forum.predix.io/questions/17406/px-dependency-hell.html#comment-17506)

<img width="1110" alt="screen shot 2017-01-26 at 09 23 30" src="https://cloud.githubusercontent.com/assets/19690117/22326068/22f09d66-e3a9-11e6-931e-c10493a51d5e.png">

**Comment by runn-vermel** [comment]
Hi @dwarhya - That sounds like a different issue.

Doing a rm-rf bower-components, bower cache clean, and making sure you have the latest versions of the components SHOULD take care of this - we went through a big change with theming, so, if you don't have the latest of all the components, this is likely to happen.

**Comment by dwarhya** [comment]
Hi Runn

I did all that you said below.  The font is still wrong.  New cache is

$ bower cache list
canvg=https://github.com/shprink/canvg.git#1.3.0
d3=https://github.com/mbostock-bower/d3-bower.git#4.1.1
es6-promise=https://github.com/components/es6-promise.git#3.3.1
font-awesome=https://github.com/FortAwesome/Font-Awesome.git#4.4.0
inuit-functions=https://github.com/inuitcss/tools.functions.git#0.2.0
inuit-responsive-settings=https://github.com/inuitcss/settings.responsive.git#0.1.5
inuit-responsive-tools=https://github.com/inuitcss/tools.responsive.git#0.1.3
iron-a11y-announcer=https://github.com/PolymerElements/iron-a11y-announcer.git#1.0.5
iron-a11y-keys-behavior=https://github.com/PolymerElements/iron-a11y-keys-behavior.git#1.1.9
iron-behaviors=https://github.com/polymerelements/iron-behaviors.git#1.0.17
iron-collapse=https://github.com/PolymerElements/iron-collapse.git#1.3.0
iron-dropdown=https://github.com/PolymerElements/iron-dropdown.git#1.5.5
iron-fit-behavior=https://github.com/PolymerElements/iron-fit-behavior.git#1.2.5
iron-flex-layout=https://github.com/polymerelements/iron-flex-layout.git#1.3.1
iron-icon=https://github.com/PolymerElements/iron-icon.git#1.0.12
iron-iconset-svg=https://github.com/PolymerElements/iron-iconset-svg.git#1.1.0
iron-input=https://github.com/polymerelements/iron-input.git#1.0.10
iron-meta=https://github.com/polymerelements/iron-meta.git#1.1.2
iron-overlay-behavior=https://github.com/polymerelements/iron-overlay-behavior.git#1.10.2
iron-pages=https://github.com/PolymerElements/iron-pages.git#1.0.8
iron-resizable-behavior=https://github.com/PolymerElements/iron-resizable-behavior.git#1.0.5
iron-selector=https://github.com/PolymerElements/iron-selector.git#1.5.2
iron-validatable-behavior=https://github.com/PolymerElements/iron-validatable-behavior.git#1.1.1
moment=https://github.com/moment/moment.git#2.13.0
moment=https://github.com/moment/moment.git#2.17.1
moment-timezone=https://github.com/moment/moment-timezone.git#0.5.11
neon-animation=https://github.com/polymerelements/neon-animation.git#1.2.4
numbro=https://github.com/foretagsplatsen/numbro.git#1.9.3
numbro-element=https://github.com/MeTaNoV/numbro-element.git#1.0.4
polymer=https://github.com/Polymer/polymer.git#1.7.1
px=https://github.com/PredixDev/px.git#1.4.3
px-buttons-design=https://github.com/predixDev/px-buttons-design.git#1.1.4
px-card=https://github.com/PredixDev/px-card.git#0.6.4
px-colors-design=https://github.com/predixDev/px-colors-design.git#0.3.4
px-context-browser=https://github.com/PredixDev/px-context-browser.git#1.6.2
px-data-table=https://github.com/predixdev/px-data-table.git#1.15.10
px-datetime-common=https://github.com/PredixDev/px-datetime-common.git#0.7.5
px-defaults-design=https://github.com/predixDev/px-defaults-design.git#1.0.3
px-demo-data=https://github.com/PredixDev/px-demo-data.git#0.0.20
px-dropdown=https://github.com/predixDev/px-dropdown.git#2.2.6
px-forms-design=https://github.com/predixDev/px-forms-design.git#1.1.4
px-functions-design=https://github.com/predixDev/px-functions-design.git#1.0.8
px-iconography-design=https://github.com/predixDev/px-iconography-design.git#0.3.8
px-layout-design=https://github.com/predixDev/px-layout-design.git#0.4.3
px-list-bare-design=https://github.com/predixDev/px-list-bare-design.git#0.3.2
px-list-inline-design=https://github.com/predixDev/px-list-inline-design.git#0.3.2
px-list-ui-design=https://github.com/predixDev/px-list-ui-design.git#1.1.3
px-meta-lists-design=https://github.com/predixDev/px-meta-lists-design.git#0.4.1
px-mixins-design=https://github.com/predixDev/px-mixins-design.git#0.3.2
px-overlay=https://github.com/predixDev/px-overlay.git#0.4.2
px-polymer-font-awesome=https://github.com/PredixDev/polymer-font-awesome.git#0.1.11
px-polymer-font-awesome=https://github.com/PredixDev/polymer-font-awesome.git#1.1.2
px-popover=https://github.com/PredixDev/px-popover.git#1.7.2
px-spacing-design=https://github.com/predixDev/px-spacing-design.git#0.4.2
px-spinner=https://github.com/PredixDev/px-spinner.git#0.5.3
px-tabs=https://github.com/PredixDev/px-tabs.git#0.6.3
px-theme=https://github.com/PredixDev/px-theme.git#2.0.3
px-tooltip=https://github.com/PredixDev/px-tooltip.git#0.10.9
px-typography-design=https://github.com/predixDev/px-typography-design.git#1.2.3
px-validation=https://github.com/predixDev/px-validation.git#0.4.3
px-vis=https://github.com/PredixDev/px-vis.git#0.8.6
px-vis-timeseries=https://github.com/PredixDev/px-vis-timeseries.git#0.6.7
web-animations-js=https://github.com/web-animations/web-animations-js.git#2.2.2
webcomponentsjs=https://github.com/Polymer/webcomponentsjs.git#0.7.23

Lee
