### ISSUE TITLE
texts and the custom components are overlapping if header texts are long length

### ISSUE THREAD

**Issue by satishpoul** [PredixDev/px-context-browser#33]
Hi Team,

If text in headers are longer, custom components existing at right side overlaps with this text.
following screenshot will clear the scenario. 
![2](https://cloud.githubusercontent.com/assets/3095213/22148026/cfd8cb9c-df31-11e6-8c56-b98f476e7403.jpg)

**Comment by runn-vermel** [comment]
Hi @satishpoul 

the context browser is designed to take up the entire length of its container - if you put it in a smaller container, this shouldn't happen.

I'm going to close this, please re-open if this doesn't solve your issue.
