### ISSUE TITLE
Label field is not reflecting on breadcrumb.

### ISSUE THREAD

**Issue by swapnilk0607** [PredixDev/px-context-browser#37]
## Expected behavior and actual behavior:

In px-context-browser when we set label-field to different field other than name, the change is reflecting on Context Browser, but Breadcrumbs still shows the name.

Ideally, Asset label which we see in context browser ,same label should be there in bread crumbs

## Steps to reproduce the problem:
1. Pass label-field to px-context-browser other than name. e.g. identifier

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):
Component Version : 1.6.2
Browser : Chrome 56 , IE 11

## Screenshots (_optional, but very helpful_):
![image](https://cloud.githubusercontent.com/assets/11830321/23891005/3cfff176-08ba-11e7-9ebb-7a55b9db3e2d.png)

## Code examples 
```html
<px-context-browser label-field="identifier" id-field="identifier" opened-item-name="Select Context" show-chevron="true"></px-context-browser>
```

**Comment by randyaskin** [comment]
Fixed in v1.6.10
