### ISSUE TITLE
Filtering is not clearing when change another parent object and elements lost when go back

### ISSUE THREAD

**Issue by lmesta** [PredixDev/px-context-browser#40]
Hi Predix Team

I encounter an issue , when filtering objects in the context browser

When i have 3 columns in the context browser and filter in the third column
it display the filtered values but
if i don't clear the filter value in the third column
and change to another item in the first column
when i try to comeback to my previous selection is only displaying the filtered values that i left before 
and not all the children items

**Comment by runn-vermel** [comment]
Can you create a codepen to help understand the problem please?

**Comment by randyaskin** [comment]
Closing due to age / lack of response. Reopen if you can reproduce in isolation.
