### ISSUE TITLE
When adding assets during user creation/editing, user cannot select the enterprise or site that is at the bottom of the list

### ISSUE THREAD

**Issue by imdam** [PredixDev/px-context-browser#41]
When adding assets during user creation/editing, user cannot select the enterprise or site that is at the bottom of the list. There should be vertical scroll bar so that user can scroll to the bottom and pick the enterprise or site. See screenshot attached.

Steps:
Login with admin permission. Go to Administrator.
Create a new user. Select one of the permission set.
Click on drop down botton to select an Asset.
Click on all resources

Result: Notice that if you many enterprise or sites, then you are able to scroll down and pick the one that is at the bottom of the list.

![asset permission](https://cloud.githubusercontent.com/assets/11979882/24365902/70c1018c-12e5-11e7-8e67-49afa6e48789.jpg)

**Comment by runn-vermel** [comment]
You should have a scrollbar built in - which version are you using?

**Comment by randyaskin** [comment]
Not able to replicate this. Even when items are dynamically added into the context browser, the overflow properly provides a scrollbar automatically.
