### ISSUE TITLE
scroll Issue

### ISSUE THREAD

**Issue by Dhawal0693** [PredixDev/px-context-browser#42]
If there are many assets in application that the scrollbar appears and now when user scrolls down and reaches the end of the scroll there is a call for getChildren even though user has not clicked on any of the asset. Why is it so?

The use case for my project doesn't require this automatic call when it has reached the end while user is scrolling. Is there any way to disable on-scroll function that calls getChildren at the end?

## Expected behavior and actual behavior:
There should be a call to getChildren only when user clicks on any asset.
## Steps to reproduce the problem:
Log into any application that has many assets and try to scroll to the end and observe that there is a call for getChildren

**Comment by randyaskin** [comment]
Runn fixed this in v1.7.0.
