### ISSUE TITLE
Console Errors for SVG

### ISSUE THREAD

**Issue by satishpoul** [PredixDev/px-context-browser#45]
# Various console errors.

Hi,

I am getting lot of errors in console for loading svg images. Issue is about violating content security policy directive.
Follwoing is the screen shot for one of them. 

![console_errors](https://user-images.githubusercontent.com/3095213/27328679-97d10046-55d0-11e7-9142-679e26d3b57e.jpg)

following is one of the exact link of svg element present in console errors. (can copy and paste in browsers to try)

_data:image/svg+xml;charset=US-ASCII,<svg%20xmlns%3D"http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg"%20width%3D"12"%20viewBox%3D"0%200%20658%201024"><path%20fill%3D"%233b3b3f"%20d%3D"M614.286%20420.571q0%207.429-5.714%2013.143l-266.286%20266.286q-5.714%205.714-13.143%205.714t-13.143-5.714l-266.286-266.286q-5.714-5.714-5.714-13.143t5.714-13.143l28.571-28.571q5.714-5.714%2013.143-5.714t13.143%205.714l224.571%20224.571%20224.571-224.571q5.714-5.714%2013.143-5.714t13.143%205.714l28.571%2028.571q5.714%205.714%205.714%2013.143z"%2F><%2Fsvg>_

Please me to solve the problem

**Comment by randyaskin** [comment]
Can you isolate this in a standalone repository or CodePen? I'm not able to replicate it in the context browser demo page, and the px-context-browser doesn't actually use SVG anywhere in its codebase.

**Comment by davidrleonard** [comment]
Closing since we weren't able to get a reproducible case.
