### ISSUE TITLE
Open Arrow should be persistent in panel header.

### ISSUE THREAD

**Issue by ppeyro** [PredixDev/px-context-browser#46]
## Expected behavior and actual behavior:

When open arrow is added to the list of actionable icon, it should be persistent in panel header like favorites/select icons are.  Not the case currently.

## Environment:

CB: redesign branch/latest pull
Browser: Chrome59

## Screenshot :

![open_in_header](https://user-images.githubusercontent.com/10835611/27972219-6e3883f2-630a-11e7-9e08-1bac53a9a773.png)

/cc @davidrleonard

**Comment by davidrleonard** [comment]
Closing, not in spec. Thanks :)
