### ISSUE TITLE
Duplicated id's should generate an error/warning.

### ISSUE THREAD

**Issue by ppeyro** [PredixDev/px-context-browser#47]
## Expected behavior and actual behavior:
Duplicated id's are not generating an error/warning, e.g.: 

```       
            "label": "Scottsdale",
            "id": "Scottie",
            "children": [
              {
                "label": "Country Club1",
                "id": "SC1",
                "hasChildren": true
              },
              {
                "label": "Country Club2",
                "id": "SC1",
                "hasChildren": false
              }
```

## Environment:
CB: Redesign branch/latest pull
Chrome: 59

## Screenshot:
![no_warning_dupids](https://user-images.githubusercontent.com/10835611/27972655-f9434fa8-630b-11e7-9287-94b60cd84ec8.png)

/cc @davidrleonard

**Comment by davidrleonard** [comment]
We're going to punt on providing warnings and focus on good docs for this. Rolling up into the demo/docs catch-all issue #68.
