### ISSUE TITLE
Chevron should be resized

### ISSUE THREAD

**Issue by ppeyro** [PredixDev/px-context-browser#49]
## Expected behavior and actual behavior:
Size of the chevron should be resized to match the design.  It's currently much larger.

## Environment :

CB: Redesign branch/latest pull
Browser: Chrome59

### Design:
![design_chevron](https://user-images.githubusercontent.com/10835611/27973055-79520e54-630d-11e7-9061-369f21c75847.png)

### Implemented Version:
![code_chevron](https://user-images.githubusercontent.com/10835611/27973065-84e63ca4-630d-11e7-99e6-f2962c1e81d5.png)

/cc @davidrleonard

**Comment by davidrleonard** [comment]
Fixed in 5b47ac4c0ab2b878bc3fd46078e5dd21778a5ceb, its smaller now to match the spec.
