### ISSUE TITLE
Hover over select icon should color match the design.

### ISSUE THREAD

**Issue by ppeyro** [PredixDev/px-context-browser#50]
## Expected behavior and actual behavior:
On a selected item, hovering over the up arrow icon doesn't match the design spec.

## Environment:

CB: redesign branch, latest pull
Browser: Chrome59

### Design

![selected_hover_design](https://user-images.githubusercontent.com/10835611/27973617-84d00ffe-630f-11e7-95c2-ce838dde3965.png)

### Implemented Version:
![selected_hover_code](https://user-images.githubusercontent.com/10835611/27973621-8a789520-630f-11e7-963f-e3c5ba553bb1.png)

/cc @davidrleonard

**Comment by davidrleonard** [comment]
Fixed in c7c647123d3670cddb823ef8cd19aabec4924d01, confirmed colors with Wade and added to the specification document.
