### ISSUE TITLE
Order of icons should match the design.

### ISSUE THREAD

**Issue by ppeyro** [PredixDev/px-context-browser#51]
## Expected behavior and actual behavior:
When all actionable icons are present, their order should be switched to match the design.

## Environment 
CB: redesign branch/latest pull
Browser: chrome59

### Design
![icon_order_design](https://user-images.githubusercontent.com/10835611/27973852-5be56430-6310-11e7-8e4a-5f74d0edbabe.png)

### Implemented
![icon_order_code](https://user-images.githubusercontent.com/10835611/27973863-6648b922-6310-11e7-8b74-31748e99a8f7.png)

/cc @davidrleonard

**Comment by davidrleonard** [comment]
Fixed in 6110c34e9135d770e9c7200e8e18865ed5a4d247
