### ISSUE TITLE
Jittering on hover when open arrow is present

### ISSUE THREAD

**Issue by ppeyro** [PredixDev/px-context-browser#52]
## Expected behavior and actual behavior:

When open arrow is configured into the CB, there seems to be a jittering effect when hovering over the icons as the open arrow appears/disappears and the rest of the icons are redrawn.

Can't attach the clip, but see screenshots for the open arrow presence/removal on hover.

## Environment:

CB: Redesign Branch/latest pull
Browser: Chrome

## Screenshots:
![jitter_1](https://user-images.githubusercontent.com/10835611/27974157-98bc2e4c-6311-11e7-9827-c984f3c789e5.png)

![jitter_2](https://user-images.githubusercontent.com/10835611/27974161-9ea3e318-6311-11e7-85e2-1c02d43f1430.png)

/cc @davidrleonard

**Comment by davidrleonard** [comment]
Should be fixed as of add0e088970083da728f0c59be67adab6f783845
