### ISSUE TITLE
Setting hasChildren to false is not removing the open arrow from the actionable icons.

### ISSUE THREAD

**Issue by ppeyro** [PredixDev/px-context-browser#53]
## Expected behavior and actual behavior:

Setting hasChildren to false should remove the open arrow from the actionable icons since there will be no children for that node, but that doesn't seem to be the case.

## Environment:

CB: Redesign branch/latest pull
Browser: Chrome59

## Screenshots:

![betatech_json](https://user-images.githubusercontent.com/10835611/27975618-e457fc4a-6317-11e7-98b3-76ce6ff33f8c.png)

Implemented:

![betatech_arrow](https://user-images.githubusercontent.com/10835611/27975630-ee54db14-6317-11e7-8c2e-8d7627376979.png)

/cc @davidrleonard

**Comment by davidrleonard** [comment]
As of 034c8155d14408b851a898c015134342e09eb1a4, item does not show an open arrow if it is marked with `isTerminal` (aka the new name for `hasChildren`).

The following object would not show an open arrow:

```
{
  "id": "abcd",
  "label": "Label Text",
  "isTerminal" true
}
```

Know we need more docs for this. :)
