### ISSUE TITLE
Responsive & Mobile interactions should be implemented.

### ISSUE THREAD

**Issue by ppeyro** [PredixDev/px-context-browser#55]
## Expected behavior and actual behavior:
Doesn't seem like the mobile interactions have been implemented per design.  Opening this issue so we can track the future effort.
There also seems to be an issue with responsive behavior. CB doesn't quite fit in the iphone view and doesn't resize to fit as expected.

## Steps to reproduce the problem:

Open the local instance in a chrome screen size simulator.

## Environment:
CB: Redesign branch, latest pull
Browser: Chrome simulator

## Screenshot:

![iphone6_cb](https://user-images.githubusercontent.com/10835611/27979991-14754ce0-632f-11e7-9f3e-6a6b76715737.png)

/cc @davidrleonard

**Comment by davidrleonard** [comment]
Implemented in 08f93a728a49f6e34016ce581e21918bbb9791b7
