### ISSUE TITLE
Fade in/out Animations look jittery in FF

### ISSUE THREAD

**Issue by ppeyro** [PredixDev/px-context-browser#57]
## Expected behavior and actual behavior:
This is hard to describe and since I can't attach a clip to the issue will try to describe it. Compared to Chrome and Safari, the fadein/out animations in Firefox are jittery as if they are happening in slower speed.  Mostly noticeable in transitions when the text fading in is overlaying the existing item causing the animation to not appear smooth.

Attaching a few frames out of a clip, showing the text being overlaid during the animation. Not sure if this will help with debugging or if this is a limitation of the browser itself and can't be addressed.

## Environment:
CB: Redesign branch/dist version
Browser: FF 54.0.1

## Screenshots:

![screen shot 2017-07-10 at 12 19 52 pm](https://user-images.githubusercontent.com/10835611/28035980-677f6158-656b-11e7-8681-cf8eac4f9e17.png)

![screen shot 2017-07-10 at 12 20 40 pm](https://user-images.githubusercontent.com/10835611/28035988-6d4966a6-656b-11e7-88a9-de8079f27957.png)

![screen shot 2017-07-10 at 12 19 15 pm](https://user-images.githubusercontent.com/10835611/28035995-7191732a-656b-11e7-87a1-8a07f7810ac6.png)

/cc @davidrleonard

**Comment by davidrleonard** [comment]
I can reproduce this. I'll leave it open for the future, pushing it down the road for now to focus on other issues.

**Comment by davidrleonard** [comment]
Fixed as of 63d123746b924559b9c54703fdf06c4b5dc61cb5, when we switched from WebAnimations API to using good old fashioned CSS animations.
