### ISSUE TITLE
Panel height/width issue when selecting an item, in Safari9

### ISSUE THREAD

**Issue by ppeyro** [PredixDev/px-context-browser#58]
## Expected behavior and actual behavior:

Safari9, when an item is selected in the panel, the height/width of the panel can shrink causing a vertical & horizontal scrollbar to appear overlaying the last item in the panel.
Doesn't seem to happen on the main panel, but as you navigate down to the children view, it seems to happen.

## Environment:

CB: Redesign branch
app-helpers: multi branch

Browser: Safari 9

## Screenshot:

![screen shot 2017-07-10 at 1 23 33 pm](https://user-images.githubusercontent.com/10835611/28038536-160c0368-6574-11e7-8c98-a4c60702ab5a.png)

**Comment by davidrleonard** [comment]
I can't reproduce this. Can you? It may have been fixed in one of the CSS refactors. If it is no longer happening, we can go ahead and close the issue.

**Comment by ppeyro** [comment]
Looks like no longer reproducible.  Closing this out.
