### ISSUE TITLE
Documentation Required

### ISSUE THREAD

**Issue by AnirbanKundu** [PredixDev/px-context-browser#6]
Some documentation about context browser's data structure will be very helpful

**Comment by nonmetalhail** [comment]
@carlosfhernandez Can you create a rally story for this?

**Comment by baspete** [comment]
I agree with Anirban. Your example shows using iron-ajax for data retrieval and binding--that's not particularly helpful for all the GE folks using Angular. Please provide documentation for the framework we all use.

**Comment by 212361828** [comment]
+1 I know seed is going away from Angular but we have an awful lot of apps that use it and that doesn't look to be changing for some time.

**Comment by mdwragg** [comment]
Hey @baspete,

We've got this example in the old Angular [Predix Seed](https://github.com/PredixDev/predix-seed/), fancy helping me shorted it/simplify it and we can add it to this repo? I started it but wasn't sure what the cleanest way to do it in Angular was - I'd appreciate your expertise in the matter.

Cheers.

https://github.com/PredixDev/predix-seed/blob/develop/public/scripts/modules/sample-module/predix-asset-service.js

https://github.com/PredixDev/predix-seed/blob/develop/public/scripts/modules/sample-module/dashboard-controller.js

https://github.com/PredixDev/predix-seed/blob/develop/public/views/dashboards.html

**Comment by baspete** [comment]
Sure @mdwragg, I'd love to help. I don't think we need to use a whole, heavyweight seed app to do it, though. Just a simple one-page angular app should be fine. I'll try and take a look when I get some time.

**Comment by mdwragg** [comment]
That's great, thanks @baspete! Once we've got a simple and clean pattern we can use that in other repos to show how best to use in an Angular environment. I think that would make all our lives easier!

**Comment by runn-vermel** [comment]
@baspete - have you had a chance to create this example we can incorporate into the component?
