### ISSUE TITLE
px-context-browser-typeahead placeholder default text needs to be localized

### ISSUE THREAD

**Issue by timmystokes** [PredixDev/px-context-browser#60]
## Expected behavior and actual behavior:
placeholder="Filter" within px-context-browser-typeahead should be localized using the localize method

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):
Px-Context-Browser Version 1.8

## Screenshots (_optional, but very helpful_):
<img width="594" alt="screen shot 2017-07-11 at 3 23 35 pm" src="https://user-images.githubusercontent.com/13026093/28093846-25f2587e-664e-11e7-9546-7c61b5f989f8.png">

**"Filter"** search box

<img width="814" alt="screen shot 2017-07-11 at 3 23 03 pm" src="https://user-images.githubusercontent.com/13026093/28093847-25f4d87e-664e-11e7-9ba9-443503bf7e57.png">

Thanks!

**Comment by randyaskin** [comment]
Based on the old pre-Cirrus version of C.B. but @talimarcus is working on this for the latest version.

**Comment by talimarcus** [comment]
PR is out @timmystokes, should be ready soon: https://github.com/PredixDev/px-context-browser/pull/95
