### ISSUE TITLE
Selected-route is not selecting the specified route.

### ISSUE THREAD

**Issue by ppeyro** [PredixDev/px-context-browser#61]
## Expected behavior and actual behavior:

Tried to preselect a route using the "selected-route" attribute, but the route doesn't seem to get pre-selected as expected.  

## Environment:
CB: Redesign branch - today's pull
App-helpers: Master - today's pull

## Screenshot:
![screen shot 2017-07-11 at 3 53 44 pm](https://user-images.githubusercontent.com/10835611/28094402-413c9bfa-6651-11e7-88aa-c3a08c35fd1c.png)

## Code example:

```
        <px-context-browser
            selected-route='["Sy1DFzRs_ENTERPRISE","r1TutzRs_SITE"]'
            items="{{data}}"
            selected="{{selectedItem}}"
            has-filter
            open-arrow
            has-favorites
            loading-timeout=0
            enable-warnings
            >
        </px-context-browser>
```

/cc @davidrleonard

**Comment by davidrleonard** [comment]
Fixed in: 

* px-context-browser b9b55e8d74ff6e74880699d0b051b5520b585e0b
* https://github.com/PredixDev/px-app-helpers/commit/0671ec15ff82d7fbe08b44b1ad7e1432d649c271
