### ISSUE TITLE
Navigating to children is broken in IE11.

### ISSUE THREAD

**Issue by ppeyro** [PredixDev/px-context-browser#64]
When the context browser is opened in IE11 any attempt to navigate to a child node, sometimes works but with an error in the log, and most times it has and unpredictable behavior, pointing to a null child and removing the parent from the header.

## Steps to reproduce the problem:
Navigate to any child

## Environment:
CB: Redesign Branch/today's pull
app-helpers: Master/today's pull

Browser: IE11 on a win7

## Screenshots :
![2017-07-14_1229](https://user-images.githubusercontent.com/10835611/28228603-0dfebfe4-6894-11e7-90bd-5f05daf439c0.png)

/cc @davidrleonard

**Comment by davidrleonard** [comment]
This specific error was fixed in fe5133d5f454672cf302cdd38c1cda72362d69d2 by adding the Promise polyfill directly to the context browser. There is a different navigation bug that continues toi be an issue — clicking on the parent in the header fails.

**Comment by davidrleonard** [comment]
It seems like there are not child navigation bugs with IE11 after 63d123746b924559b9c54703fdf06c4b5dc61cb5. Closing.
