### ISSUE TITLE
Promise is undefined error when selected-route is present in IE11 only.

### ISSUE THREAD

**Issue by ppeyro** [PredixDev/px-context-browser#65]
Getting a different behavior in IE11 with the same Config test file (has selected-route defined in its config).  The context browser is missing the panel on IE11 in and gets a promise undefined error compared to other browsers running the same config.

## Environment :

CB: Redesign Branch/today's pull
app-helpers: Master/today's pull

Browser: IE11 on win7 

## Screenshots:

###Test config on IE11

![2017-07-14_1321](https://user-images.githubusercontent.com/10835611/28229610-42be5876-6898-11e7-87e9-17f860c74443.png)

###Test config on Chrome

![screen shot 2017-07-14 at 1 22 58 pm](https://user-images.githubusercontent.com/10835611/28229592-32583dc6-6898-11e7-961c-6f30cc7c30ab.png)

## Code examples 

```
<px-context-browser-trigger trigger="{{trigger}}">  </px-context-browser-trigger>

        <px-context-browser
            selected-route='["Sy1DFzRs_ENTERPRISE","r1TutzRs_SITE"]'
            items="{{data}}"
            selected="{{selectedItem}}"
            open-trigger="{{trigger}}"
            has-filter
            open-arrow
            has-favorites
            loading-timeout= 0
            enable-warnings
            >
        </px-context-browser>

`````

/cc @davidrleonard

**Comment by davidrleonard** [comment]
Fixed as of 63d123746b924559b9c54703fdf06c4b5dc61cb5, no longer an issue at the tip of master.
