### ISSUE TITLE
While loading children is in progress, canceling out by selecting the header panel jumps up 2 levels instead of 1.

### ISSUE THREAD

**Issue by ppeyro** [PredixDev/px-context-browser#66]
## Expected behavior and actual behavior:

When navigating to the child level, while the "in progress bar" is active, selecting the panel header would cause the child loading to cancel out as expected, but it jumps back 2 levels up(back to grandparent) instead of 1 level(parent).

## Environment:

CB: Redesign Branch/today's pull
app-helpers: Master/today's pull
Browsers: All

## Screenshots:

![screen shot 2017-07-14 at 4 20 30 pm](https://user-images.githubusercontent.com/10835611/28234248-69a7bd50-68b2-11e7-8f6d-cde7796c1313.png)

![screen shot 2017-07-14 at 4 20 35 pm](https://user-images.githubusercontent.com/10835611/28234252-715b5958-68b2-11e7-8cf0-b6da6585b159.png)

/cc @davidrleonard

**Comment by davidrleonard** [comment]
Fixed as of 63d123746b924559b9c54703fdf06c4b5dc61cb5, no longer an issue at the tip of master.
