### ISSUE TITLE
Mobile: Navigating back to the top level, always has the filter selected and the virtual keyboard opened.

### ISSUE THREAD

**Issue by ppeyro** [PredixDev/px-context-browser#72]
## Expected behavior and actual behavior:

When navigating back from children back to the top level parent by tapping on the panel header, when you land at the top level browser panel, the filter shows as selected and virtual keyboard is opened.

This is happening in mobile both portrait and landscape modes.

## Environment:

CB: master pull latest with mobile implementation today
Browser: Safari on iphone plus, ios 10.3.1

## Screenshot:

![img_0020](https://user-images.githubusercontent.com/10835611/28588638-0368aec4-7130-11e7-8841-077870d4baa1.png)

/cc @davidrleonard

**Comment by davidrleonard** [comment]
@ppeyro Was the filter active before you tapped the header?

**Comment by ppeyro** [comment]
That would be a negative... :) 
No filter was active at the time.

**Comment by ppeyro** [comment]
Seems like if you tap and hold for a bit longer,  or tap like u really mean it... it will make it happen.
