### ISSUE TITLE
Remove references to multiActivate and multiSelect from docs.

### ISSUE THREAD

**Issue by ppeyro** [PredixDev/px-context-browser#75]
Summary says it all...

**Comment by randyaskin** [comment]
As a reminder, you can use the `hide` property like I've done [here](https://github.com/PredixDev/px-breadcrumbs/blob/d0a1f4a2fcf2cb4061831cf015f86323a0845eb4/demo/index.html#L57).

**Comment by talimarcus** [comment]
Fixed in #77
