### ISSUE TITLE
Can't update items in Context Browser

### ISSUE THREAD

**Issue by talimarcus** [PredixDev/px-context-browser#79]
When I update the items in the context browser, they show up in the DOM, but not in the CB itself. 

1. Update the items in the Code Editor on the demo page

![screen shot 2017-07-28 at 4 14 06 pm](https://user-images.githubusercontent.com/9092541/28739558-c5237d50-73b0-11e7-99f9-8c97cc6972ad.png)

3. Open the CB -- the items were not updated

![screen shot 2017-07-28 at 4 14 18 pm](https://user-images.githubusercontent.com/9092541/28739557-c5216c72-73b0-11e7-8782-3e1ab7581d43.png)

3. But... look at the items in the DOM -- apparently they were updated

![screen shot 2017-07-28 at 4 19 30 pm](https://user-images.githubusercontent.com/9092541/28739566-d1997cba-73b0-11e7-8bd4-ab363be94ec4.png)

4.  Update the `selectedRoute` to one of the new item ids (e.g. "da")

![screen shot 2017-07-28 at 4 17 25 pm](https://user-images.githubusercontent.com/9092541/28739573-da662bd6-73b0-11e7-8a30-62ac2ec4456c.png)

5. You will get a console error saying "The route ["da"] could not be found in the items graph."

![screen shot 2017-07-28 at 4 19 23 pm](https://user-images.githubusercontent.com/9092541/28739544-b0695e52-73b0-11e7-90b4-c94fedd7076c.png)

**Comment by davidrleonard** [comment]
I think this is fixed now. Can you confirm so we can close @talimarcus?

**Comment by talimarcus** [comment]
Fixed :+1:
