### ISSUE TITLE
Scrolling issue with lazy loading mode

### ISSUE THREAD

**Issue by stephanepilla** [PredixDev/px-context-browser#8]
There is an issue in the context browser in lazy loading mode when the children item list is too long for the column (ie : when a scrollbar is used in the column) :

When an asset has many children, they will all be displayed in the same column in the browser after the internal call to getChildren (using my custom promise assigned to getChildren handler).
In that case, the current column will have a scrollbar.

If you scroll down to the bottom of the column (for example with your mouse wheel), there is an anormal behavior in the browser : the getChildren handler will be called many unneccessary times for the parent asset.

.

**Comment by stephanepilla** [comment]
This can actually be handled with the 'total' attribute in the meta data.

However, the spinner never disappears when all the children are finally read.

**Comment by runn-vermel** [comment]
Fixed with PR #9
