### ISSUE TITLE
Minor edits in CT browser's documentation.

### ISSUE THREAD

**Issue by ppeyro** [PredixDev/px-context-browser#84]
Super nitpicky issue....

Here are screenshots for edits that may be needed:
![screen shot 2017-08-29 at 1 54 46 pm](https://user-images.githubusercontent.com/10835611/29846512-08659b32-8ccc-11e7-82ff-a662031ee1bd.png)

![screen shot 2017-08-29 at 2 31 22 pm](https://user-images.githubusercontent.com/10835611/29846517-1125d214-8ccc-11e7-8c3a-7cc6ffeaa03f.png)

![screen shot 2017-08-29 at 2 40 40 pm](https://user-images.githubusercontent.com/10835611/29846531-21471464-8ccc-11e7-817a-46d91012bfb2.png)

![screen shot 2017-08-29 at 2 45 11 pm](https://user-images.githubusercontent.com/10835611/29846536-29e35506-8ccc-11e7-8817-b781be47ca0c.png)

![screen shot 2017-08-29 at 2 54 17 pm](https://user-images.githubusercontent.com/10835611/29846548-32ce4bf8-8ccc-11e7-958b-69b46af76ad1.png)

**Comment by talimarcus** [comment]
Fixed in https://github.com/PredixDev/px-app-helpers/commit/dcd427b70efc3e80298415ad955ebbee459438f7
