### ISSUE TITLE
Documentation for older versions of the component

### ISSUE THREAD

**Issue by akshayeshenoi** [PredixDev/px-context-browser#85]
Hi,

I see that this component has had a major overhaul post version 2.\*.\* and the documentation has been updated accordingly. There might be a need for developers to access older documentation. For example, `browser-context` was used to populate the items (at least in version 1.6.7). Now, `items` is used, and with the name change, the format has also changed. 

I have been trying to figure out the format and its explanation by selecting an older commit and digging deep into the demo files. This is very time consuming. 

Can you please keep legacy documentation public?

Thanks.

**Comment by randyaskin** [comment]
As I answered via the forums, the front page of predix-ui.com contains a link to archive.predix-ui.com, which houses the documentation for the pre-redesign (last major version) of our components. We do not currently maintain live builds for all versions of the documentation, I imagine that would be technically cumbersome.
