### ISSUE TITLE
Not able to integrate context browser 2.0.10 with angular 1.5.8

### ISSUE THREAD

**Issue by Shibham** [PredixDev/px-context-browser#88]
Hi,

I am trying to integrate predix compoent  px-context-browser 2.0.20 eith Angular 1.5.8 but not able to do that. The trigger is not getting attached to the context browser. Can anyone help on this please?

**Comment by davidrleonard** [comment]
This is pretty simple. `px-context-browser` accepts an `openTrigger` property, which is a reference to a `px-context-browser-trigger` found somewhere on the page. The reference should be to the `px-context-browser-trigger` HTMLElement, or to the element's `trigger` property (which is just a convenient way to bing to the HTMLElement). 

There are a lot of ways to do this in Angular depending on where you're using the context browser. You could use the $element service in an Angular 1.5 component's controller to find the `px-context-browser` and `px-context-browser-trigger` HTMLElement references inside the Angular component. Then you could set the `px-context-browser` property `openTrigger` to a reference to the trigger.

Here is a simplified example of this working: https://angular-1-px-context-browser.glitch.me/
Here is the code for the example: https://glitch.com/edit/#!/angular-1-px-context-browser?path=views/index.html:58:7

I didn't know how Angular 1.5's components or $element service worked. I searched for those on Google and found the following articles to create the example above:

* https://docs.angularjs.org/guide/component
* https://docs.angularjs.org/api/ng/function/angular.element
* https://toddmotto.com/exploring-the-angular-1-5-component-method/
