### ISSUE TITLE
showFavorited property cannot be set false.

### ISSUE THREAD

**Issue by leebickmtu** [PredixDev/px-context-browser#99]
The `showFavorited` property is not able to be set false.

Since boolean properties are set by the presence of the attribute or not and the property is defaulted to `true` not having the attribute present doesn't turn off favorites..

The requirement for configurable boolean properties to default to `false` is documented in both the Polymer 1.x and 2.x docs.
https://www.polymer-project.org/1.0/docs/devguide/properties#configuring-boolean-properties
https://www.polymer-project.org/2.0/docs/devguide/properties#configuring-boolean-properties

**Comment by talimarcus** [comment]
Good catch @leebickmtu, fixing now.

**Comment by talimarcus** [comment]
Fixed in v2.2.0
